import { Action, createReducer, on } from '@ngrx/store';
import { ILinkParserState } from '../types/linkParserState.interface';
import {
  parseLinkAction,
  parseLinkFailureAction,
  parseLinkSuccessAction,
} from './parseLink.action';

const initialState: ILinkParserState = {
  errors: null,
  isSubmitting: false,
  products: [
    {
      name: '\n        витамин D3, 125 мкг (5000 МЕ), 360 капсул из рыбьего желатина\n    ',
      brand: 'California Gold Nutrition',
      regularPrice: 3478,
      superPrice: null,
      weight: 0.17,
      imageLink: 'https://s3.images-iherb.com/cgn/cgn01066/v/119.jpg',
      link: 'https://by.iherb.com/pr/california-gold-nutrition-vitamin-d3-125-mcg-5-000-iu-360-fish-gelatin-softgels/70317',
      qty: 1,
    },
    {
      name: '\n        BioCoenzymated, B6, пиридоксал-5-фосфат, 50 мг, 30 вегетарианских капсул\n    ',
      brand: 'Natural Factors',
      regularPrice: 1197,
      superPrice: null,
      weight: 0.08,
      imageLink: 'https://s3.images-iherb.com/nfs/nfs01252/v/43.jpg',
      link: 'https://by.iherb.com/pr/natural-factors-biocoenzymated-b6-pyridoxal-5-phosphate-50-mg-30-vegetarian-capsules/78242',
      qty: 2,
    },
    {
      name: "\n        BioCoenzymated, B2, рибофлавин 5'-фосфат, 50 мг, 30 вегетарианских капсул\n    ",
      brand: 'Natural Factors',
      regularPrice: 1197,
      superPrice: null,
      weight: 0.08,
      imageLink: 'https://s3.images-iherb.com/nfs/nfs01249/v/41.jpg',
      link: 'https://by.iherb.com/pr/natural-factors-biocoenzymated-b2-riboflavin-5-phosphate-50-mg-30-vegetarian-capsules/78240',
      qty: 2,
    },
    {
      name: '\n        витамин K (MK-4, MK-6, MK-7, MK-9), 120 мкг, 60 растительных капсул\n    ',
      brand: 'California Gold Nutrition',
      regularPrice: 2557,
      superPrice: null,
      weight: 0.05,
      imageLink: 'https://s3.images-iherb.com/cgn/cgn01299/v/87.jpg',
      link: 'https://by.iherb.com/pr/california-gold-nutrition-vitamin-k2-mk-4-mk-6-mk-7-mk-9-120-mcg-60-veggie-capsules/86957',
      qty: 1,
    },
    {
      name: 'KAL, Lithium Orotate, 5 mg, 120 VegCaps',
      link: 'https://by.iherb.com/pr/kal-lithium-orotate-5-mg-120-vegcaps/85528',
      qty: 1,
      isNotAvailable: true,
    },
    {
      name: '\n        фермент папайи, 100 жевательных таблеток\n    ',
      brand: '21st Century',
      regularPrice: 759,
      superPrice: null,
      weight: 0.11,
      imageLink: 'https://s3.images-iherb.com/cen/cen22662/v/23.jpg',
      link: 'https://by.iherb.com/pr/21st-century-papaya-enzyme-chewable-100-tablets/3354',
      qty: 1,
    },
    {
      name: '\n        Цитрат кальция, 1000 мг, 90 таблеток\n    ',
      brand: 'KAL',
      regularPrice: 2887,
      superPrice: null,
      weight: 0.24,
      imageLink: 'https://s3.images-iherb.com/cal/cal57109/v/8.jpg',
      link: 'https://by.iherb.com/pr/kal-calcium-citrate-1-000-mg-90-tablets/106641',
      qty: 1,
    },
    {
      name: '\n        витамин D3 повышенной силы действия, 125 мкг (5000 МЕ), 100 быстрорастворимых таблеток MicroLingual\n    ',
      brand: 'Superior Source',
      regularPrice: 2717,
      superPrice: null,
      weight: 0.03,
      imageLink: 'https://s3.images-iherb.com/sps/sps90860/v/3.jpg',
      link: 'https://by.iherb.com/pr/superior-source-extra-strength-vitamin-d3-125-mcg-5-000-iu-100-microlingual-instant-dissolve-tablets/26974',
      qty: 1,
    },
    {
      name: 'Solaray, White Willow, 400 mg, 100 VegCaps',
      link: 'https://by.iherb.com/pr/solaray-white-willow-400-mg-100-vegcaps/70035',
      qty: 1,
      isNotAvailable: true,
    },
    {
      name: '\n        BlueRich, супер эффективность, концентрат голубики, 500 мг, 90 мягких таблеток\n    ',
      brand: 'Natural Factors',
      regularPrice: 2154,
      superPrice: null,
      weight: 0.21,
      imageLink: 'https://s3.images-iherb.com/nfs/nfs04516/v/22.jpg',
      link: 'https://by.iherb.com/pr/natural-factors-bluerich-super-strength-blueberry-concentrate-500-mg-90-softgels/7049',
      qty: 1,
    },
    {
      name: '\n        MegaFolinic, 800 мкг, 120 таблеток\n    ',
      brand: 'Source Naturals',
      regularPrice: 2578,
      superPrice: null,
      weight: 0.06,
      imageLink: 'https://s3.images-iherb.com/sns/sns02028/v/20.jpg',
      link: 'https://by.iherb.com/pr/source-naturals-megafolinic-800-mcg-120-tablets/7735',
      qty: 1,
    },
    {
      name: '\n        витамин B12, метилкобаламин, 1000 мкг, 90 жевательных таблеток\n    ',
      brand: 'Natural Factors',
      regularPrice: 1797,
      superPrice: null,
      weight: 0.08,
      imageLink: 'https://s3.images-iherb.com/nfs/nfs01242/v/17.jpg',
      link: 'https://by.iherb.com/pr/natural-factors-b12-methylcobalamin-1-000-mcg-90-chewable-tablets/2521',
      qty: 1,
    },
    {
      name: '\n        MK-7, витамин K2, 100 мкг, 60 растительных капсул\n    ',
      brand: 'Now Foods',
      regularPrice: 3034,
      superPrice: null,
      weight: 0.05,
      imageLink: 'https://s3.images-iherb.com/now/now00992/v/36.jpg',
      link: 'https://by.iherb.com/pr/now-foods-mk-7-vitamin-k-2-100-mcg-60-veg-capsules/36220',
      qty: 2,
    },
    {
      name: '\n        натуральный лецитин, 1365 мг, 180 мягких желатиновых капсул\n    ',
      brand: 'Bluebonnet Nutrition',
      regularPrice: 4286,
      superPrice: null,
      weight: 1.08,
      imageLink: 'https://s3.images-iherb.com/blb/blb00926/v/17.jpg',
      link: 'https://by.iherb.com/pr/bluebonnet-nutrition-natural-lecithin-1-365-mg-180-softgels/12026',
      qty: 1,
    },
  ],
};

const parseLinkReducer = createReducer(
  initialState,
  on(
    parseLinkAction,
    (state): ILinkParserState => ({
      ...state,
      isSubmitting: true,
      errors: null,
    }),
  ),
  on(
    parseLinkSuccessAction,
    (state, action): ILinkParserState => ({
      ...state,
      isSubmitting: false,
      errors: null,
      products: action.products,
    }),
  ),
  on(
    parseLinkFailureAction,
    (state, action): ILinkParserState => ({
      ...state,
      isSubmitting: false,
      errors: action.errors,
      products: [],
    }),
  ),
);

export function reducer(state: ILinkParserState, action: Action) {
  return parseLinkReducer(state, action);
}
